server.port: ${PORT:9999}

spring:
  datasource:
    hikari:
      schema: user
      auto-commit: true
      username: root
      password: race@2007
      jdbc-url: jdbc:mysql://localhost:3306/user
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    properties.hibernate:
      format_sql: false
      show_sql: true
    hibernate:
      ddl-auto: update



app:
  password:
    secret:
      key: "test1234" #